version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    env_file:
      - env/django.env
      - env/postgres.env
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - postgres

volumes:
  pgdata: